import{S as q,a as M,i}from"./assets/vendor-BtI-3F0k.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const p=document.querySelector(".gallery"),f=document.querySelector(".loader-container"),h=document.querySelector(".load-more-btn"),P=new q(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:n,comments:w,downloads:v})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${a}">
            <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
          </a>
          <div class="info-box">
            <p class="info-item">Likes<span>${r}</span></p>
            <p class="info-item">Views<span>${n}</span></p>
            <p class="info-item">Comments<span>${w}</span></p>
            <p class="info-item">Downloads<span>${v}</span></p>
          </div>
        </li>
      `).join("");p.insertAdjacentHTML("beforeend",t),P.refresh()}function B(){p.innerHTML=""}function g(){f.classList.remove("is-hidden")}function y(){f.classList.add("is-hidden")}function l(){h.classList.remove("is-hidden")}function d(){h.classList.add("is-hidden")}const $="https://pixabay.com/api",R="47550347-a44441999a35f73cd42751acc";async function L(o,t){return(await M.get($,{params:{key:R,q:o,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const S=document.querySelector(".form"),x=document.querySelector(".load-more-btn");let u="",c=1;const b=15;S.addEventListener("submit",O);async function O(o){o.preventDefault();const t=o.currentTarget.elements["search-text"].value.trim();if(t){u=t,c=1,B(),d(),g();try{const s=await L(u,c);if(s.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(s.hits),s.totalHits<=b?(d(),i.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):l()}catch(s){console.error(s),i.error({message:"Something went wrong!",position:"topRight"})}finally{y(),S.reset()}}}x.addEventListener("click",H);async function H(){c+=1,d(),g();try{const o=await L(u,c);m(o.hits);const t=document.querySelector(".gallery-item");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}const s=Math.ceil(o.totalHits/b);c>=s?i.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):l()}catch(o){console.error(o),i.error({message:"Something went wrong!",position:"topRight"}),l()}finally{y()}}
//# sourceMappingURL=index.js.map
