import{S as q,a as M,i as l}from"./assets/vendor-BtI-3F0k.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const d=document.querySelector(".gallery"),u=document.querySelector(".loader-container"),f=document.querySelector(".load-more-btn"),P=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:n,comments:v,downloads:w})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${a}" alt="${e}" loading="lazy" />
          </a>
          <div class="info-box">
            <p class="info-item">Likes<span>${r}</span></p>
            <p class="info-item">Views<span>${n}</span></p>
            <p class="info-item">Comments<span>${v}</span></p>
            <p class="info-item">Downloads<span>${w}</span></p>
          </div>
        </li>
      `).join("");d.insertAdjacentHTML("beforeend",t),P.refresh()}function B(){d.innerHTML=""}function m(){u.classList.remove("is-hidden")}function h(){u.classList.add("is-hidden")}function y(){f.classList.remove("is-hidden")}function g(){f.classList.add("is-hidden")}const $="https://pixabay.com/api",x="47550347-a44441999a35f73cd42751acc";async function L(o,t){return(await M.get($,{params:{key:x,q:o,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:"true"}})).data}const b=document.querySelector(".form"),O=document.querySelector(".load-more-btn");let c="",i=1;const S=15;b.addEventListener("submit",H);async function H(o){o.preventDefault();const t=o.currentTarget.elements["search-text"].value.trim();if(t){c=t,i=1,B(),g(),m();try{const a=await L(c,i);if(a.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(a.hits),a.totalHits>S&&y()}catch(a){console.error(a)}finally{h(),b.reset()}}}O.addEventListener("click",A);async function A(){i+=1,m();try{const o=await L(c,i);p(o.hits);const t=document.querySelector(".gallery-item");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}const a=Math.ceil(o.totalHits/S);i>=a?(g(),l.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):y()}catch(o){console.error(o)}finally{h()}}
//# sourceMappingURL=index.js.map
